spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reminder_dev_db?useSSL=false&serverTimezone=UTC
    username: root 
    password: "{cipher}4e4956653ee629921d618159a53c8953527f163f69e83c8b450fac60e7266678c617df59de988b6000d396504d3a1870" 
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa: 
    hibernate: 
      ddl-auto: update 
    show-sql: true 
    properties: 
      hibernate:
        format-sql: true 
        dialect: org.hibernate.dialect.MySQL8Dialect 
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh, env 
  endpoint: 
    health:
      show-details: always 
logging:
  level:
    root: INFO 
    org.springframework.web: WARN 
    com.azscode.reminder_service: DEBUG 