spring:
  datasource:
    url: jdbc:h2:mem:devreminderdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa: 
    hibernate: 
      ddl-auto: update 
    show-sql: true 
    properties: 
      hibernate:
        format-sql: true 
        dialect: org.hibernate.dialect.MySQL8Dialect 
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh, env 
  endpoint: 
    health:
      show-details: always 
logging:
  level:
    root: INFO 
    org.springframework.web: WARN 
    com.azscode.reminder_service: DEBUG 