spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/todo_db?useSSL=true&requireSSL=true&verifyServerCertificate=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: "{cipher}87f8e945d4c0bb7ea9a2eb46afe8ce3b8d3fb95c8c4a9a15f3bf98956b617aaa"
    password: "{cipher}b526f98c1f52d1e4c555870a3e417508ed28d398f514ef7cae59aacee481e4340165a6b0a74eda784b77936317109ef6"
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa: 
    hibernate: 
      ddl-auto: validate 
    show-sql: false 
    properties: 
      hibernate:
        format-sql: false 
        dialect: org.hibernate.dialect.MySQL8Dialect 
management:
  endpoints:
    web: 
      exposure:
        include: health, info 
  endpoint:
    health:
      show-details: when_authorized 
logging:
  level:
    root: INFO 
    org.springframework.web: DEBUG 
    com.azscode.reminder_service: DEBUG 